// Mocks generated by Mockito 5.3.2 from annotations
// in potentium_test/test/albums_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:potentium_test/bloc/fetch_albums/fetch_albums_bloc.dart' as _i2;
import 'package:potentium_test/repository/albums_repository.dart' as _i3;

import 'albums_list_widget_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchAlbumsState_0 extends _i1.SmartFake
    implements _i2.FetchAlbumsState {
  _FakeFetchAlbumsState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlbumRepository_1 extends _i1.SmartFake
    implements _i3.AlbumRepository {
  _FakeAlbumRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockMyBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockMyBloc extends _i1.Mock implements _i4.MockMyBloc {
  MockMockMyBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FetchAlbumsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFetchAlbumsState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FetchAlbumsState);
  @override
  _i5.Stream<_i2.FetchAlbumsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.FetchAlbumsState>.empty(),
      ) as _i5.Stream<_i2.FetchAlbumsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i3.AlbumRepository get albumRepository => (super.noSuchMethod(
        Invocation.getter(#albumRepository),
        returnValue: _FakeAlbumRepository_1(
          this,
          Invocation.getter(#albumRepository),
        ),
      ) as _i3.AlbumRepository);
  @override
  set albumRepository(_i3.AlbumRepository? _albumRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #albumRepository,
          _albumRepository,
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i2.FetchAlbumsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i2.FetchAlbumsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void add(_i2.FetchAlbumsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i2.FetchAlbumsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i2.FetchAlbumsEvent>(
    _i6.EventHandler<E, _i2.FetchAlbumsState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i6.Transition<_i2.FetchAlbumsEvent, _i2.FetchAlbumsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
}
